runtime: python
env: flex
entrypoint: gunicorn -b :$PORT manage:app

runtime_config:
  python_version: 3

# App Engine flexible Python 3 runtime uses Python 3.7.x, which supports both
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10